### ISSUE TITLE
In 2-3, floating balloon crate does not crush Loris.

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#1]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _Loris is crushed under floating crate if it is pushed down onto them._

**Actual Result:** _Nothing happens._
![capture2](https://user-images.githubusercontent.com/31082660/37375999-44cf2896-2776-11e8-8ca8-26e4ba5ede62.PNG)

**Comment by heatblayze** [comment]
Fixed. Reviewing changes.

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
