### ISSUE TITLE
In 2-1, Loris can climb electrified cable without dying

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#10]
**Location:** _2-1_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (20/03/18)_

_In 2-1, Loris can climb electrified cable without dying._
![bug6](https://user-images.githubusercontent.com/31082660/37632828-238206e0-2c44-11e8-9287-095d3455a92f.gif)

**Comment by Wickedarc** [comment]
pending review

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
