### ISSUE TITLE
In 2-5, the camera does not vertically track the loris when he climbs ropes

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#13]
**Location:** _2-5_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (21/03/18)_

_In 2-5, the camera does not vertically track the loris when he climbs ropes_
![bug10](https://user-images.githubusercontent.com/31082660/37687580-32661b68-2cf0-11e8-9c6d-331eea5d3644.gif)

**Comment by heatblayze** [comment]
Temporary fix: moved camera out. All levels will have full splines for all events soon.

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
