### ISSUE TITLE
In 2-3, Trampoline puts both Poodle & Loris into infinite loop

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#14]
**Location:** _2-3_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (21/03/18)_
**Priority** _2 (High)_

_In 2-3, Trampoline puts both Poodle & Loris into infinite loop. Loris should get launched behind the trampoline, Poodle should get stuck in infinite loop until far trampoline is moved._
![bug11](https://user-images.githubusercontent.com/31082660/37694231-981d26b2-2d19-11e8-8b3d-e9383964da2a.gif)

**Comment by heatblayze** [comment]
Loris now lands behind, poodle on top (default positions)

**Comment by LachlanRMMorrow** [comment]
Fixed, but created a new and even more exciting bug 👌
