### ISSUE TITLE
In 2-5, Loris cannot exit level & walks through far wall

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#15]
**Location:** _2-5_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (21/03/18)_
**Priority:** _3 (Medium)_

_In 2-5, Loris cannot exit level & walks through far wall. See attatched .gif_
![bug12](https://user-images.githubusercontent.com/31082660/37695230-cadd63ac-2d21-11e8-9d97-e880b8320a9f.gif)

**Comment by Wickedarc** [comment]
pending review

**Comment by LachlanRMMorrow** [comment]
Partially fixed. Can't walk through the wall now but still can't exit the level.

**Comment by LachlanRMMorrow** [comment]
Fully fixed 👌
