### ISSUE TITLE
In 2-5, Loris sometimes dies when jumping down from button platform

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#16]
**Location:** _2-5)_
**Reproducibility:** _Sometimes_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (26/03/18)_
**Priority:** _2(High)_

_In 2-5, Loris sometimes dies when jumping down from button platform. Will look into a level design solution to this problem before resorting to a programming solution._
![bug13](https://user-images.githubusercontent.com/31082660/37880777-4d4e3644-30d9-11e8-94d7-39f2435eecf5.gif)

**Comment by LachlanRMMorrow** [comment]
Might be able to force the player to move the circular box to break the Loris' fall. Box is currently unmovable so will need to get @heatblayze or @Wickedarc to fix that.

**Comment by heatblayze** [comment]
That circular :bowtie: box can now be moved, if that's good enough

**Comment by LachlanRMMorrow** [comment]
Forksed 👌
