### ISSUE TITLE
In 2-4, Ropes to reach trap chest are un-interactable

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#19]
**Location:** _2-4_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor_Current_
**Priority:** _3(Medium)_

_In 2-4, Ropes to reach trap chest are un-interactable_
![bug16](https://user-images.githubusercontent.com/31082660/37880986-838d23b6-30dc-11e8-8f03-5045a99141e3.gif)

**Comment by LachlanRMMorrow** [comment]
Not fixed. Still seems to be happening. 😕

**Comment by heatblayze** [comment]
Done 🙃

**Comment by LachlanRMMorrow** [comment]
Fixed it this time 👌 💯 🎉 🌮
