### ISSUE TITLE
In 2-3, Floating balloon crate bobs up and down for a long time after being climbed off

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#2]
## Bug occurring in Editor. Not Tested in Build.

**Expected Result:** _Floating balloon crate returns to resting position in a reasonable amount of time after being climbed off._

**Actual Result:** _Floating balloon crate bobs up and down for a long time after being climbed off._
![bug1](https://user-images.githubusercontent.com/31082660/37376225-781786ac-2777-11e8-95ce-84f39a1db903.gif)

**Comment by heatblayze** [comment]
Fixed in latest version

**Comment by heatblayze** [comment]
Moving to "for review" instead of closed

**Comment by LachlanRMMorrow** [comment]
Fixed. Thanks @heatblayze.
