### ISSUE TITLE
Many missing camera splines in 2-7

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#21]
**Location:** _2-7_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (26/03/18)_
**Priority:** _2(High)_

_Many missing camera splines in 2-7. 2 shown in attached gif, more likely missing throughout the rest of the level._
![ezgif com-gif-maker 3](https://user-images.githubusercontent.com/31082660/37881159-71309bdc-30df-11e8-9936-94a35d68470d.gif)

**Comment by heatblayze** [comment]
Please note, the splines aren't missing. They're just broken lol

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
