### ISSUE TITLE
Game runs at 1 fps in 2-8

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#22]
**Location:** _2-8_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (26/03/18)_
**Priority:** _2(High)_

_Game runs at 1 fps in 2-8._
![bug19](https://user-images.githubusercontent.com/31082660/37881200-fddf5582-30df-11e8-992d-f8cbbde35590.gif)

**Comment by heatblayze** [comment]
Is this in editor or build? If editor, that's probably a Unity bug (known issue in our version)

**Comment by LachlanRMMorrow** [comment]
In editor. I'll mark it as resolved if we already know about it and can't fix it.

**Comment by heatblayze** [comment]
(turns out this was actually from my commit where I turned the water off never being submitted and eventually being disregarded)
((but also an editor bug is present btw, not lying about that lol))
