### ISSUE TITLE
When animals fall from platforms they generally are not followed by a camera spline

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#25]
**Location:** _Multiple levels, observed in 2-7 & 2-4_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (26/03/18)_
**Priority:** _3 (Medium)_

_When animals fall from platforms they generally are not followed by a camera spline_
![bug22](https://user-images.githubusercontent.com/31082660/37885547-9991b3fa-3101-11e8-8bd5-48dd0ab221a0.gif)

**Comment by heatblayze** [comment]
You added this bug just after I submitted a fix for it lol

**Comment by LachlanRMMorrow** [comment]
This has been fixed in the example I gave in the gif, but it still happens a lot in other levels.
![bug27](https://user-images.githubusercontent.com/31082660/37936109-07619dd4-31a0-11e8-9d9a-d2ecf6e82868.gif)

**Comment by LachlanRMMorrow** [comment]
Fixed in this example I guess 👌
