### ISSUE TITLE
When tongue bridge is active and character is switched, the anteater cancels the tongue bridge and returns to idle state

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#26]
**Location:** _2-7_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (26/03/18)_
**Priority:** _2(High)_

_When tongue bridge is active and character is switched, the anteater cancels the tongue bridge and returns to idle state_
![bug23](https://user-images.githubusercontent.com/31082660/37885924-a8aabf6a-3103-11e8-9a43-0a977be1ed24.gif)

**Comment by heatblayze** [comment]
Fixed that. Also fixed the bridge not building

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
