### ISSUE TITLE
When Poodle is carrying the loris and falls, the loris moves up while the poodle moves down

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#27]
**Location:** _2-3_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _0.1.52_
**Priority:** _4(Low)_

_When Poodle is carrying the loris and falls, the loris moves up while the poodle moves down. Doesn't seem to be level specific._
![bug24](https://user-images.githubusercontent.com/31082660/37886086-8681a664-3104-11e8-975e-d46ac605d8c0.gif)

**Comment by LachlanRMMorrow** [comment]
Still happening.

**Comment by heatblayze** [comment]
Because... I forgot to submit on github lol

**Comment by LachlanRMMorrow** [comment]
Yup fixed 👌
