### ISSUE TITLE
Poodle can drop loris while turning, allowing the loris to be placed inside other objects and fall through them

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#28]
**Location:** _2-9 (Should be possible in any level)_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (27/03/18)_
**Priority:** _4(Low)_

_Poodle can drop loris while turning, allowing the loris to be placed inside other objects and fall through them_
![ezgif com-gif-maker 4](https://user-images.githubusercontent.com/31082660/37935569-bc7ecbe0-319d-11e8-9892-2cb23f5bc5f8.gif)

**Comment by heatblayze** [comment]
Loris will now do a sweeptest when being dropped. Tested this against a box and he drops to the side.

This also brings up the Animal being on the wrong z-position, which I guess can be fixed by having a main movement spline for every level (which I have to do for a couple levels anyway)

**Comment by LachlanRMMorrow** [comment]
Yeah, so I guess I can put this back into to-do and you can add in a movement spline to restrict them to that axis? @heatblayze

**Comment by LachlanRMMorrow** [comment]
Or I can just make a new bug for that. I'll just do that.
