### ISSUE TITLE
Electricity not working in 2-9

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#29]
**Location:** _2-9_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (27/03/18)_
**Priority:** _3(Medium)_

_Electricity not working in 2-9_
![bug26](https://user-images.githubusercontent.com/31082660/37935665-2298007c-319e-11e8-9e57-960092d1865c.gif)

**Comment by heatblayze** [comment]
Had empty layermask. All will now default to Animal layer if empty 👌

**Comment by LachlanRMMorrow** [comment]
Still not working 🤔

**Comment by heatblayze** [comment]
Empty layermask now adds AnimalTrigger as well. That fixed it

**Comment by LachlanRMMorrow** [comment]
Fexed et 👌
