### ISSUE TITLE
Poodle can fly and move through walls now I guess?

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#30]
**Location:** _2-3_
**Reproducibility:** _Unable to reproduce_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (27/03/18)_
**Priority:** _3(Medium)_

_Poodle can fly and move through walls now I guess? I don't even know where to start with this one fam. No idea what caused this to happen._
![ezgif com-optimize](https://user-images.githubusercontent.com/31082660/37936772-713a0550-31a2-11e8-8318-add383bfd5f8.gif)

**Comment by heatblayze** [comment]
Could have been from my missing push? I can't reproduce this either

**Comment by LachlanRMMorrow** [comment]
I feel like this is fixed
