### ISSUE TITLE
Animals can be moved off their correct z-axis

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#32]
**Location:** _Observed in 2-9_
**Reproducibility:** _Sometimes_
**Blocks gameplay:** _No_
**Version (if known):** _Editor - Current (27/03/18)_
**Priority:** _4(Low)_

_Animals can be moved off their correct z-axis_
![bug30](https://user-images.githubusercontent.com/31082660/37946543-abe2c0be-31d1-11e8-8ecf-444cc459d592.gif)

**Comment by heatblayze** [comment]
((((((((((**self note: add walking splines for the levels**))))))))))

**Comment by heatblayze** [comment]
Fixed in current area 2 levels where this is possible.

**Comment by LachlanRMMorrow** [comment]
Looks good 👌
