### ISSUE TITLE
In 2-5, if Poodle walks into the trick wardrobe then walks back out, when they jump on the table they can't move right

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#34]
**Location:** _2-5_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (28/03/18)_
**Priority:** _3(Medium)_

_In 2-5, if Poodle walks into the trick wardrobe then walks back out, when they jump on the table they can't move left_
![bug32](https://user-images.githubusercontent.com/31082660/38001148-ff1d47f4-3276-11e8-9d8b-39c2993b56b6.gif)

**Comment by heatblayze** [comment]
(that's left btw)

**Comment by LachlanRMMorrow** [comment]
Yeah I noticed and edited it as soon as I submitted it

**Comment by heatblayze** [comment]
It's ok I still fixed it for u bb <3

**Comment by LachlanRMMorrow** [comment]
Sure did <3 <:sugar:428372980381253642>
