### ISSUE TITLE
Anteater sinks into the floor during sitting animation

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#35]
**Location:** _Observed in 2-6_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (28/03/18)_
**Priority:** _5(Very Low)_

_Anteater sinks into the floor during sitting animation_
![bug33](https://user-images.githubusercontent.com/31082660/38001558-2a340cdc-3279-11e8-954d-5aad8d62b403.gif)

**Comment by heatblayze** [comment]
(I don't think this has been pushed yet)

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
