### ISSUE TITLE
When controlling the poodle, W & S trigger the loris' climb animation if they are on a ladder

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#36]
**Location:** _Observed in 2-7_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (28/03/18)_
**Priority:** _5(Very Low)_

_When controlling the poodle, W & S trigger the loris' climb animation if they are on a ladder_
![bug34](https://user-images.githubusercontent.com/31082660/38001928-45d9aac6-327b-11e8-91b2-04bc723cc206.gif)

**Comment by heatblayze** [comment]
The fix I made _should_ also fix any movement animations when not selected (unless forced movement)

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
