### ISSUE TITLE
In 2-7, when the loris interacts with the tongue bridge they are teleported to the top of the ladder

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#37]
**Location:** _2-7_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current(28/03/18)_
**Priority:** _3(Medium)_

_In 2-7, when the loris interacts with the tongue bridge they are teleported to the top of the ladder_
![bug35](https://user-images.githubusercontent.com/31082660/38002012-ae65a6bc-327b-11e8-9bb6-eba036f53fdc.gif)

**Comment by heatblayze** [comment]
Can't replicate after fixing #38 , assuming it was the same issue.

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
