### ISSUE TITLE
In 2-1, crate can be pushed without interacting with it or activating the push animation

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#4]
**Location:** _2-1_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Build 0.8.2b_

_When playing at Priscilla in 2-1, the crate at the beginning of the level can be moved just by walking into it and without interacting with it or triggering the push animation._
![ezgif com-gif-maker](https://user-images.githubusercontent.com/31082660/37626935-2efade66-2c26-11e8-9b4b-a992347b06c5.gif)

**Comment by Wickedarc** [comment]
Solved issue, currently under review

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
