### ISSUE TITLE
In 2-7, Anteater can't exit level

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#40]
**Location:** _2-7_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (28/03/18)_
**Priority:** _3(Medium)_

_In 2-7, Anteater can't exit level_
![bug38](https://user-images.githubusercontent.com/31082660/38006054-235f122e-328f-11e8-950b-0f3f5afb7ec1.gif)

**Comment by heatblayze** [comment]
I moved the exit box 5cm across <:YEET:421525383511408651>

**Comment by LachlanRMMorrow** [comment]
Fixed <:sugar:428372980381253642>
