### ISSUE TITLE
In 2-8, Pressing space with the Loris while on a specific platform snaps the loris to the ladder 

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#41]
**Location:** _2-8_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (28/03/18)_
**Priority:** _3(Medium)_

_In 2-8, Pressing space with the Loris while on a specific platform snaps the loris to the ladder. See gif for details_
![bug39](https://user-images.githubusercontent.com/31082660/38010363-6abd3276-32a4-11e8-8087-48a49c4ccd68.gif)

**Comment by heatblayze** [comment]
ez pz <a:ditto:428424151456546816>

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
