### ISSUE TITLE
Electricity is not properly configured in 2-2

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#43]
**Location:** _2-2_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (04/04/18)_
**Priority:** _2(High)_

_Electricity is not properly configured in 2-2._
- [ ] Probuilder boxes denoting the electricity AOE should be turned off when the electricity is turned off
- [ ] Vanity should start electrified, Floor should start disabled. Plug/lever should swap the states of these two electrical zones.

**Comment by Wickedarc** [comment]
Fixed, Under Review

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
