### ISSUE TITLE
In 2-3, Loris falls through shelf when fired from the cannon

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#44]
**Location:** _2-3_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (04/04/18)_
**Priority:** _3(Medium)_

_In 2-3, Loris falls through shelf when fired from the cannon. Refer to attached .gif_
![bug42](https://user-images.githubusercontent.com/31082660/38281687-30a52e2c-37ef-11e8-9c41-7f89fa810893.gif)

**Comment by LachlanRMMorrow** [comment]
Fixed <:sugar:428372980381253642>

**Comment by LachlanRMMorrow** [comment]
That platform is fixed but now the one with the peanut chest has the same issue.

**Comment by Wickedarc** [comment]
Fixed?

**Comment by LachlanRMMorrow** [comment]
Yup, Fixed <:sugar:428372980381253642>
