### ISSUE TITLE
Collider is not connected to mesh for medium crate in 2-3

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#45]
**Location:** _2-3_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (04/04/18)_
**Priority:** _3(Medium)_

_Collider is not connected to mesh for medium crate in 2-3._
![bug43](https://user-images.githubusercontent.com/31082660/38282908-12091f58-37f6-11e8-8b4d-3ea65d9c0895.gif)

**Comment by Wickedarc** [comment]
Pending Review

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
