### ISSUE TITLE
Camera not properly configured in 2-5 (P2)

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#46]
**Location:** _2-5_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (04/04/18)_
**Priority:** _2(High)_

_Camera not properly configured in 2-5. See attached .gif_
![bug44](https://user-images.githubusercontent.com/31082660/38283142-b7cc99fa-37f7-11e8-8226-46c67a60e7aa.gif)

**Comment by LachlanRMMorrow** [comment]
Moved up to Priority 2.

**Comment by Wickedarc** [comment]
pending review

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
