### ISSUE TITLE
Anteater Gets Pushed through Floor (P3)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#47]
**Location:** _2-9_
**Reproducibility:** _Sometimes_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-current-4/04/2018_
**Priority:** _3(Medium)_
![falling glitch](https://user-images.githubusercontent.com/29085981/38283332-d5b06e8c-37f8-11e8-9e77-c647b995feee.gif)

If Anteater walk under lift after lift is already been raised up and then the player drops the lift. The lift pushes the Anteater through the floor.

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
