### ISSUE TITLE
Magician's hat does not teleport the loris in 2-5 (P2)

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#48]
**Location:** _2-5_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (06/04/18)_
**Priority:** _2(High))_

_Magician's hat does not teleport the loris in 2-5._
![bug45](https://user-images.githubusercontent.com/31082660/38403621-2f88f98c-39a8-11e8-902e-4d11d2f34d98.gif)

**Comment by LachlanRMMorrow** [comment]
@Wickedarc needs help from @heatblayze to fix this.

**Comment by heatblayze** [comment]
Somebody poisoned the trigger box!

**Comment by heatblayze** [comment]
i.e. it was just on the wrong layer

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
