### ISSUE TITLE
Climbing up the stairs in 2-5 with Priscilla seems to break the splines (P2)

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#49]
**Location:** _2-5_
**Reproducibility:** _Sometimes
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor_Current-(09/04/18)_
**Priority:** _2(High)_

_Climbing up the stairs in 2-5 with Priscilla seems to break the splines. Refer to linked .gif_
https://media.giphy.com/media/14vFmi6GWoDgzBRP5M/giphy.gif

**Comment by heatblayze** [comment]
All should be well now. Found the possible cause and can no longer reproduce it

**Comment by LachlanRMMorrow** [comment]
Fixed, 2-5 fully playable again <:YEET:421525383511408651>
