### ISSUE TITLE
Animation when grabbing PPObject

### ISSUE THREAD

**Issue by Wickedarc** [EarlyWormGames/SkedaddleBugs#5]
**Location:** _Level number (any level with PPObject)_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current_

_ Turn to face the opposite direction from a PPObject and grab in the same instance_
![capture](https://user-images.githubusercontent.com/22251055/37627911-d4337510-2c2a-11e8-976d-63ee3ea770ca.gif)

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
