### ISSUE TITLE
Level Select images need to be updated (P4)

### ISSUE THREAD

**Issue by Wickedarc** [EarlyWormGames/SkedaddleBugs#51]
Location: Pause > Level select menu
Reproducibility: Always
Blocks gameplay:  No
Version (if known): 0.7.04
Priority:  4(Low)

Image dont represent levels correctly

![1](https://user-images.githubusercontent.com/22251055/38531404-01993b1e-3cb3-11e8-8cb4-33db60033f38.PNG)

**Comment by Wickedarc** [comment]
Pending Review

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
