### ISSUE TITLE
Poodle should not be able to drop loris while turning (P3)

### ISSUE THREAD

**Issue by Wickedarc** [EarlyWormGames/SkedaddleBugs#52]
Location: All levels with the poodle and loris
Reproducibility: Always 
Blocks gameplay: Possibly?
Version (if known): 0.7.04
Priority:  3(Medium)

Causes issues with splines and where laurie is walking

**Comment by heatblayze** [comment]
Legit didn't even add any lines of code to fix this lmao

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
