### ISSUE TITLE
Nightvision doesn't work properly (P3)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#54]
Location: 2-1
Reproducibility: Always 
Blocks gameplay: No
Version (if known): 0.7.04
Priority: 3(Meduim)

Loris Nightvision does not improve vision in dark, Poodle can see things easier than Loris can.
![poodle view](https://user-images.githubusercontent.com/29085981/38597419-f2e850d0-3d9a-11e8-8186-9b91d7e28923.PNG)
![loris view](https://user-images.githubusercontent.com/29085981/38597421-f6c159c2-3d9a-11e8-86aa-be0fa694db3d.PNG)

**Comment by LachlanRMMorrow** [comment]
Added appropriate tags/updated priority where appropriate.

**Comment by LachlanRMMorrow** [comment]
Fixed by @Retr0mancer 👌
