### ISSUE TITLE
Loris Misalignment (P4)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#55]
Location: 2-2
Reproducibility: Always
Blocks gameplay: No
Version (if known): 0.7.04
Priority: 4(Low)

When climbing down from the peanut chest, loris will land on the edge of the clothes rack, not the middle.

**Comment by LachlanRMMorrow** [comment]
Added appropriate tags/updated priority where appropriate.

**Comment by Wickedarc** [comment]
uhhhhhh, wheres the clothes rack in 2-2? i think the level set dressing changed and someone had removed it......

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
