### ISSUE TITLE
Floor too low (P4)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#56]
Location: 2-3
Reproducibility: Always
Blocks gameplay: No
Version (if known): 0.7.04
Priority: 4 (Low)

Animals clip through floor, Loris is only half visible.

**Comment by LachlanRMMorrow** [comment]
Added appropriate tags/updated priority where appropriate.

**Comment by Wickedarc** [comment]
Pending Review

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
