### ISSUE TITLE
Cannon Bounces on Trampoline (P2)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#57]
Location: 2-3
Reproducibility: Always
Blocks gameplay: Yes
Version (if known): 0.7.04
Priority: 2(High)

if Loris pulls back trampoline too far, Cannon bounces on trampoline.
![boing](https://user-images.githubusercontent.com/29085981/38598103-639a659a-3d9e-11e8-89f3-e50fce15bf2d.gif)

**Comment by LachlanRMMorrow** [comment]
Added appropriate tags/updated priority where appropriate.

**Comment by LachlanRMMorrow** [comment]
Not fixed. Loris can still launch the cannon by moving onto the cannon spline while dragging the trampoline.
![bug49](https://user-images.githubusercontent.com/31082660/38961843-cdbdc772-43ad-11e8-8e77-7614b234fe78.gif)

**Comment by heatblayze** [comment]
Separate issue. Making new card.
