### ISSUE TITLE
In 2-1, Loris can not climb electrified cable after it is turned off

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#6]
**Location:** _2-1_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current_

_Loris can't climb the electrified cable after it is unplugged._
![bug2](https://user-images.githubusercontent.com/31082660/37629726-8745e95e-2c34-11e8-8304-bd4f1c75c07e.gif)

**Comment by Wickedarc** [comment]
pending review

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
