### ISSUE TITLE
Can't move toy box crate in 2-4 (P3)

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#62]
**Location:** _2-4_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (19/04/18)_
**Priority:** _3(Medium)_

_The player can't move the toy box crate in 2-4._

**Comment by heatblayze** [comment]
BEEP BEEP LETTUCE

**Comment by LachlanRMMorrow** [comment]
Fixed 👍
