### ISSUE TITLE
Moving the circular box in 2-5 pushes the poodle into the ground (P3)

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#64]
**Location:** _2-5_
**Reproducibility:** _Sometimes_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (19/04/18)_
**Priority:** _3(Medium)_

_Moving the circular box in 2-5 pushes the poodle into the ground._

**Comment by heatblayze** [comment]
Collision issues. Fixed 👌

**Comment by LachlanRMMorrow** [comment]
Fixed 👍
