### ISSUE TITLE
In 2-3 & 2-4, if the loris moves the crash mat then the poodle moves the loris, the trampoline can be swung around sending objects flying (P3)

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#67]
**Location:** _2-3 & 2-4_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (19/04/18)_
**Priority:** _3(Medium)_

_In 2-3 & 2-4, if the loris moves the crash mat then the poodle moves the loris, the trampoline can be swung around sending objects flying_
![bug 52](https://user-images.githubusercontent.com/31082660/38971745-e657127a-43df-11e8-8f70-de2c1dccbc89.gif)

**Comment by heatblayze** [comment]
I want to die 👌

**Comment by LachlanRMMorrow** [comment]
Moving back to 'To do' since work has shifted to other tasks.

**Comment by LachlanRMMorrow** [comment]
Foxed 🦊
