### ISSUE TITLE
In 2-2, Poodle can climb drawers in interactable drawer set before they have been extended

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#7]
**Location:** _2-2_
**Reproducibility:** _Always_
**Blocks gameplay:** _No_
**Version (if known):** _Editor-Current (20/03/18)_

_Before the drawers have been pulled out, animals can still climb on top of them, resulting in them clipping into the set of drawers._
![bug3](https://user-images.githubusercontent.com/31082660/37632225-4ceb1ec0-2c41-11e8-9736-78c84bfe60e4.gif)

**Comment by heatblayze** [comment]
Reviewing fix.

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
