### ISSUE TITLE
Loris can pull crashmat/trampoline onto movement spline (P2)

### ISSUE THREAD

**Issue by heatblayze** [EarlyWormGames/SkedaddleBugs#70]
Location: 2-3
Reproducibility: Always
Blocks gameplay: Yes
Version (if known): 0.7.04
Priority: 2(High)

![38961843-cdbdc772-43ad-11e8-8e77-7614b234fe78](https://user-images.githubusercontent.com/10677646/39223609-54b1519a-4886-11e8-8baa-29473c73b710.gif)

**Comment by LachlanRMMorrow** [comment]
Moving back to 'To do' since work has shifted to other tasks.

**Comment by LachlanRMMorrow** [comment]
Fickst 👌
