### ISSUE TITLE
Balloon box stays lowered after poodle climbs onto vanity (P4)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#71]
Location: 2-3
Reproducibility: Always
Blocks gameplay: No
Version (if known): Editor-current
Priority: 4(Low)

After climbing onto the balloon box in 2-3 if the Poodle climbs onto the vanity without the loris being on the box, the box will stay down as if the poodle is still on it. This stops the moment the loris climbs onto the box or the poodle walks back onto the box and walks off it in the other direction.

**Comment by Wickedarc** [comment]
Pending Review

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
