### ISSUE TITLE
2-2 Poodle Carries Clothes Trolley thru Objects (P4)

### ISSUE THREAD

**Issue by wormyg** [EarlyWormGames/SkedaddleBugs#81]
**Location:** Level number (2-2)
**Reproducibility:** Always
**Blocks gameplay:** No
**Version (if known):** Engine (12/05/2018)
**Priority:** 4(Low)
**Trello:** https://trello.com/c/ywKAJ6Pm/159-issue-81-p4

![2-2 poodle carries clothes trolley thru objects](https://user-images.githubusercontent.com/37357402/39954062-eeb39c9e-55fb-11e8-9b29-374493f53d3a.gif)

**Comment by LachlanRMMorrow** [comment]
Fixy mixy 👌
