### ISSUE TITLE
2-2 Priscilla Stuck On Vanity (P3)

### ISSUE THREAD

**Issue by wormyg** [EarlyWormGames/SkedaddleBugs#83]
**Location:** Level number (2-2)
**Reproducibility:** Always
**Blocks gameplay:** No
**Version (if known):** Engine (12/05/2018)
**Priority:** 3(Low)
**Trello:** https://trello.com/c/nh4BIwRJ/161-issue-83-p3

![2-2 priscilla stuck on dresser](https://user-images.githubusercontent.com/37357402/39954129-4b29c29a-55fd-11e8-82be-96831b0e85a9.gif)

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
