### ISSUE TITLE
2-5 Camera Broken (P4)

### ISSUE THREAD

**Issue by wormyg** [EarlyWormGames/SkedaddleBugs#87]
**Location:** Level number (2-5)
**Reproducibility:** Always
**Blocks gameplay:** No
**Version (if known):** Current (12/05/2018)
**Priority:** 4(Low)
**Trello:** https://trello.com/c/DmhMuuXl/164-issue-87-p4

Camera should be following animals.

![2-5 camera broken ii](https://user-images.githubusercontent.com/37357402/39954242-89b323ec-55ff-11e8-8003-a400c05cd9ff.gif)

![2-5 camera broken](https://user-images.githubusercontent.com/37357402/39954243-8f13c86e-55ff-11e8-8c81-6f6c816dc162.gif)

**Comment by heatblayze** [comment]
I missed one line of code <:YEET:421525383511408651>

**Comment by LachlanRMMorrow** [comment]
Fixed <:YEET:421525383511408651>
