### ISSUE TITLE
In 2-2, when Priscilla moves close enough to the exit she gets locked into walking into the exit door and cannot be controlled

### ISSUE THREAD

**Issue by LachlanRMMorrow** [EarlyWormGames/SkedaddleBugs#9]
**Location:** _2-2_
**Reproducibility:** _Always_
**Blocks gameplay:** _Yes_
**Version (if known):** _Editor-Current (20/03/18)_

_In 2-2, when Priscilla moves close enough to the exit she gets locked into walking into the exit door and cannot be controlled_
![bug5](https://user-images.githubusercontent.com/31082660/37632655-6d6d3618-2c43-11e8-93fb-90feab358132.gif)

**Comment by heatblayze** [comment]
Fixed. Reviewing changes.

**Comment by LachlanRMMorrow** [comment]
Fixed 👌
