### ISSUE TITLE
Anteater is unable to use tongue bridge. (P2)

### ISSUE THREAD

**Issue by Retr0mancer** [EarlyWormGames/SkedaddleBugs#90]
Location: 2-7
Reproducibility: Always
Blocks gameplay: Yes 
Version (if known): Current Editor
Priority: 2(High)
Trello: https://trello.com/c/99X3Iv2I/166-issue-90-p2

Anteater can't use Tongue bridge in 2-7 and can't move after trying. Furthermore an error occurs when trying which is not related to the tongue bridge but rather the LadderObject and the anteater is found under the climb trigger of the pushable ladder.
![big bug](https://user-images.githubusercontent.com/29085981/39981990-356d094a-5796-11e8-8a0f-ee6c77a006d4.PNG)

**Comment by heatblayze** [comment]
Please refer to the post I made in Discord. Just checked, it doesn't have any keys assigned to it (or an Animal that it accepts but that won't cause issues)

**Comment by heatblayze** [comment]
Also that Ladder thing is because a different Animal tried to climb the Ladder lmao (no preferred animal is set)

**Comment by heatblayze** [comment]
(nvm with the ladder that was actually me ripperoo)

**Comment by heatblayze** [comment]
Did the magical dance and fixed it all

**Comment by LachlanRMMorrow** [comment]
Flexed 💪
